on: [push, pull_request, workflow_dispatch]

name: R-CMD-release

jobs:
  R-CMD-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: install freetype2 and imagemagick deps and libreoffice
        run: brew install --cask libreoffice
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
